name: Test the Action

on:
    pull_request:
    pull_request_review:
        types:
            - submitted
    pull_request_review_comment:
        types:
            - created
            - deleted

jobs:
    # Tests that the Action works as expected.
    #
    # Performs the following steps:
    # - Checks out the repository.
    # - Runs the Action.
    test:
        name: Run Props Bot
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

            - name: Run the Action
              uses: ./
              with:
                  format: 'all'
